"""Add MMR, seasonal XP, match details

Revision ID: cae4f6170747
Revises: 4735542807c9
Create Date: 2026-03-05 22:48:04.010343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cae4f6170747'
down_revision: Union[str, Sequence[str], None] = '4735542807c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('player1_correct', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('xp_earned', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('xp_breakdown', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('seasonal_xp_series_tv', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('seasonal_xp_geographie', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('seasonal_xp_histoire', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('seasonal_total_xp', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('season_month', sa.String(length=7), nullable=True))
    op.add_column('users', sa.Column('mmr', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mmr')
    op.drop_column('users', 'season_month')
    op.drop_column('users', 'seasonal_total_xp')
    op.drop_column('users', 'seasonal_xp_histoire')
    op.drop_column('users', 'seasonal_xp_geographie')
    op.drop_column('users', 'seasonal_xp_series_tv')
    op.drop_column('matches', 'xp_breakdown')
    op.drop_column('matches', 'xp_earned')
    op.drop_column('matches', 'player1_correct')
    # ### end Alembic commands ###
